# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
stripe_api_key: sk_test_x2RWNfdwDALTYv9BD7Cuu2Pj 
stripe_publishable_key: pk_test_5qZDVW32pDebcZiEkEp1PYQs 
#
production:
  stripe_api_key: sk_test_x2RWNfdwDALTYv9BD7Cuu2Pj
  stripe_publishable_key: pk_test_5qZDVW32pDebcZiEkEp1PYQs
